apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-bbb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foo
    server: https://kubernetes.default.svc
  project: foo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: foo-bbb
      values: |
        host: foo-bbb.eon.sikademo.com
        image: sikalabs/hello-world-server:eon
        TEXT: "foo-bbb"
